name: CI

# Temporarily manual-only until setup scripts are reworked (mas hangs on CI)
on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Test setup scripts
        run: ./install.sh
